version: "3.8"

services:
  backend:
    build: ./app
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - WEBSITES_PORT=8000

  frontend:
    build: ./fe
    container_name: frontend
    environment:
      - REACT_APP_API_URL=http://backend:8000
    ports:
      - "80:80"
    depends_on:
      - backend
